#!/usr/bin/env bash

if [ -n "$BLOCK_BUTTON" ]; then
    case $BLOCK_BUTTON in
        1)  
            # left click
            $(brightnessctl set $INCREASE_BY%+)
            ;;
        3)  
            # right click
            $(brightnessctl set $INCREASE_BY%+)
            ;;
    esac
fi